### ISSUE TITLE
[console] Empty select

### ISSUE THREAD

**Issue by babakfp** [hopinc/docs#31] opened 2023-10-05 16:05 UTC
Hi

https://github.com/hopinc/docs/assets/44144724/01182ee0-5053-478a-b47b-70ef8e004cac

I expect to this be disabled or show a dropdown with a message inside it saying it's empty or something like that.

**Comment by looskie** [comment] 2023-10-05 16:54
Closing this in favor of #28 as the issue is related

**Closed as completed by looskie** 2023-10-05 16:54 UTC
